#!/usr/bin/python
# Copyright 2014 LinkedIn Corp.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

import math
import random
import time

with open("/tmp/trivial_timed_output.csv", "w") as perf_log:
  with open("/tmp/trivial_timed_output", "w") as f:
    i = ""
    while i.lower() != "quit":
      i = raw_input()
      f.write("{0} {1}\n".format(time.strftime("%Y-%m-%d %H:%M:%S"), i))
      f.flush()
      # now let's make some fake logs
      perf_log.write("{0},{1},{2}\n".format(time.strftime("%Y-%m-%d %H:%M:%S"), random.randint(80, 120), math.floor(math.sqrt(random.randint(0, 100000)))))
      perf_log.flush()
