language: python
python:
  - "2.7"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: 
 - python setup.py test -s test.test_test_runner
 - python setup.py test -s test.test_utils
 - python setup.py test -s test.test_test_runner_helper
